# Generated by Django 3.2.13 on 2023-03-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresets',
            name='created_at',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='passwordresets',
            name='email',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='passwordresets',
            name='token',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
